name: smart_menu
description: Offline QR menü uygulaması
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.0
  google_fonts: ^6.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
